name: test

on:
  push:
    branches:
      - mainnet
      - testnet
      - "release/*"
      - "feature/*"
      - "features/*"
      - "implement-feature/**"
      - "implement-feature/**/**"
  pull_request:
    branches:
      - mainnet
      - testnet
      - "release/*"
      - "feature/*"
      - "features/*"

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: [self-hosted, dockerize]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
       
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-2b1f8d6dd90f9790faf0528e05e60e573a7569ce

      - name: Install package with soldeer
        run: forge soldeer install

      - name: Recursively update dependencies
        run: |
          chmod +x ./update-deps.sh
          ./update-deps.sh
        id: update-deps

      - name: Update package with soldeer
        run: forge soldeer update

      - name: Recursively update dependencies
        run: |
          chmod +x ./update-deps.sh
          ./update-deps.sh
        id: update-deps

      - name: Run Forge build
        run: |
          forge --version
          forge build
        id: build

      - name: Run Forge tests
        run: |
          forge test --no-match-path '*forking/*' -vvv
        id: test

      - name: "Setup Node"
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 #v3.4.1
        with:
          node-version: v16.16.0