name: test

on:
  push:
    branches:
      - mainnet
      - testnet
      - "release/*"
      - "feature/*"
      - "features/*"
      - "implement-feature/**"
      - "implement-feature/**/**"
  pull_request:
    branches:
      - mainnet
      - testnet
      - "release/*"
      - "feature/*"
      - "features/*"

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: [self-hosted, dockerize]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 2
      
      - name: Get previous commit hash of target branch
        run: |
          git fetch --depth=2 origin ${{ github.ref }}
          PREV_COMMIT=$(git rev-parse HEAD~1)
          echo "Previous commit: $PREV_COMMIT"
          echo "TARGET_COMMIT_HASH=$PREV_COMMIT" >> $GITHUB_ENV

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Update package with soldeer
        run: forge soldeer update

      - name: Recursively update dependencies
        run: |
          chmod +x ./update-deps.sh
          ./update-deps.sh
        id: update-deps

      - name: Run Forge build
        run: |
          forge --version
          forge build
        id: build

      # - name: Run Forge tests
      #   run: |
      #     forge test --no-match-path '*forking/*' -vvv
      #   id: test

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref}}

      - name: "Setup Node"
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 #v3.4.1
        with:
          node-version: v16.16.0

      - name: Fetch more history
        run: |
          git fetch --unshallow || git fetch --all

      - name: Verify commit
        run: |
          if git cat-file -e d3148e01234d2e1ed1d100c82a9610432b129ac9; then
            echo "Commit exists"
          else
            echo "Commit does not exist in current history"
            git log --oneline -n 10  # Show last 10 commits
          fi

      - name: Storage Layout Check
        run: |
          forge soldeer install 
          echo "Checking storage layout..."
          echo "CURRENT_COMMIT_HASH: ${{ github.sha }}"
          echo "TARGET_COMMIT_HASH: ${{ env.TARGET_COMMIT_HASH }}"
          dependencies/@storage-delta-0.3.1/run.sh ${{ env.TARGET_COMMIT_HASH }} --omit new --contracts contracts

      - name: Check for storage_delta folder
        id: check-folder
        run: |
          if [ -d "storage_delta" ]; then
            echo "storage_delta_exists=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and changes
        if: steps.check-folder.outputs.storage_delta_exists == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add storage_delta
          git commit -m "Add contract layout changes [CI]"
          git push